repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
        exclude: ^client/
    -   id: end-of-file-fixer
        exclude: ^client/
    -   id: trailing-whitespace
        exclude: ^client/
-   repo: https://github.com/psf/black
    rev: '24.2.0'
    hooks:
    -   id: black
        exclude: ^client/
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: 'v3.0.0a5'
    hooks:
    -   id: pylint
        args: [--rcfile=.pylintrc]
        exclude: ^client/
