language: python

python:
  - "3.9"

env:
  - TRAVIS_CI=true

branches:
  only:
    - main

install:
  - pip install -r server/requirements.txt

jobs:
  include:
    - stage: test
      script: pytest server/app/tests
      name: "Server Tests"
      if: type = push AND (env(TRAVIS_CI) = true AND commit_files !~ ^server/ AND commit_files !~ ^\.travis\.yml)

    - stage: test
      script: echo "Skipping tests for client changes"
      name: "Skip Tests for Client"
      if: type = push AND (env(TRAVIS_CI) = true AND commit_files =~ ^client/)

    - stage: deploy
      script: echo "Deploying"
      name: "Deployment"
      if: type = push AND branch = main

after_success:
  - coveralls

notifications:
  email: false
