language: python

python:
  - "3.9"

env:
  - TRAVIS_CI=true

branches:
  only:
    - main

install:
  - pip install -r server/requirements.txt

script:
  - pytest server/app/tests

after_success:
  - coveralls

if: |
  type = push AND \
  ( \
    ( \
      env(TRAVIS_CI) = true AND \
      ( \
        ( \
          commit_message =~ ^server/ OR \
          commit_message =~ ^\.travis\.yml \
        ) \
      ) \
    ) \
  )

notifications:
  email: false
