language: python

python:
  - "3.9"

env:
  - TRAVIS_CI=true

branches:
  only:
    - main

install:
  - pip install -r server/requirements.txt

jobs:
  include:
    - stage: test
      script:
        - pytest server/tests
        - coverage run --source=server -m pytest server/tests
      name: "Server Tests"
      if: type = push AND env(TRAVIS_CI) = true AND TRAVIS_COMMIT_RANGE && (TRAVIS_COMMIT_RANGE !~ ^server/ AND TRAVIS_COMMIT_RANGE !~ ^\.travis\.yml)

    - stage: test
      script: echo "Skipping tests for client changes"
      name: "Skip Tests for Client"
      if: type = push AND env(TRAVIS_CI) = true AND TRAVIS_COMMIT_RANGE && TRAVIS_COMMIT_RANGE =~ ^client/

after_success:
  - coveralls

notifications:
  email: false
