language: python

python:
  - "3.9"

env:
  - TRAVIS_CI=true

branches:
  only:
    - main

install:
  - pip install -r server/requirements.txt

script:
  - pytest server/app/tests

after_success:
  - coveralls

if: (type = push) AND ((env(TRAVIS_CI) = true) OR (commit_files =~ '^server/' OR commit_files =~ '^\.travis\.yml'))

notifications:
  email: false
