"""
Module containing the predict method.
"""

from app.ml_models.model_loader import load_model

model = load_model()


def predict(features):
    """
    Predict the outcome using a machine learning model based on the input features.

    This function takes a list of features as input,
    preprocesses the features by ensuring there are at least 5 features,
    calculates the average of the first 5 features,
    and then uses a machine learning model to predict the outcome
    based on the input features.

    Args:
        features (list): A list containing the input features.

    Returns:
        object: The predicted outcome generated by the machine learning model.

    Raises:
        ValueError: If the length of the input features list is less than 5.
        ValueError: If there is an issue with the prediction process or
        if the input features are incompatible
                    with the model.
    """
    try:
        prediction = []
        for feature in features:
            while len(feature) < 5:
                feature.insert(0, 10)
            sum_of_marks = 0
            number_of_assignments = len(feature)
            while len(feature) >= 5:
                sum_of_marks += feature[0]
                feature.pop(0)
            average = round(sum_of_marks / (number_of_assignments - 4))
            feature.insert(0, average)

            prediction.append(model.predict(feature))
        return prediction

    except Exception as error:
        print(f"Error: {error}")
        raise
